
spring:
  main:
    #bean重复定义设置为true
    allow-bean-definition-overriding: true
  application:
    name: demo
  datasource:
    url: jdbc:oracle:thin:@192.168.8.128:1521:orcl
    username: crweb
    password: crweb
    driver_class_name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 600
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    poolPreparedStatements: true
  #mybatis:
  # mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: demo.entity
  #configuration:
  #  map-underscore-to-camel-case: false
  #  cache-enabled: true
  #  log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
  #  aggressive-lazy-loading: false
  #  lazy-loading-enabled: true
  #  lazy-load-trigger-methods: ""
  redis:
    database: 0  # Redis数据库索引(默认为0)
    host: localhost # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:   # Redis服务器连接密码(默认为空)
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数(使用负值表示没有限制) 默认 8
        max-wait: -1   # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1
        max-idle: 8    # 连接池中的最大空闲连接 默认 8
        min-idle: 0    # 连接池中的最小空闲连接 默认 0
    cache:
      type: redis
executor:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 10
  threadNamePrefix: cr
