server:
  port: 8090
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: demo
  datasource:
    url: jdbc:oracle:thin:@192.168.137.129:1521:helowin
    username: root
    password: root
    driver_class_name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 600
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    poolPreparedStatements: true
  redis:
    database: 0
    host: 192.168.137.129
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    cache:
      type: redis
executor:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 10
  threadNamePrefix: cr
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true
fdfs:
  connect-timeout: 600
  so-timeout: 600
  tracker-list:
    - 192.168.137.129:22122
  pool:
    max-total: 100
    max-wait-millis: 60
